CREATE TABLE DEPT2(
    DEPT_NO NUMBER (3),
    DEPT_NAME VARCHAR2(15),
    LOCA_NUMBER NUMBER (4),
    DEPT_GENDER CHAR(1),
    REG_DATE DATE,
    DEPT_BONUS NUMBER(10,5)
);

desc dept2;

INSERT Into DEPT2
values (120,'FLAK_CANNON',6612,'F',SYSDATE,2532.12423);

SELECt * FROM dept2;

ALTER TABLE DEPT2 RENAME COLUMN LOCA_NUMBER to DEPTS_LOCATION;
ALTER TABLE DEPT2 RENAME COLUMN REG_DATE to DEPTS_TODAY;
ALTER TABLE DEPT2 MOdify (DEPT_GENDER CHAR(12));
desc dept2;
update dept2
set dept_gender='Female';

SELECT*FROM dept2;