SET SERVEROUTPUT ON;
--주문(주문은 한번에 한 상품밖에 못한다고 가정)
CREATE TABLE ORDER_HISTORY (
    HISTORY_NO NUMBER(5) PRIMARY KEY,
    ORDER_NO NUMBER(5), --FK
    PRODUCT_NO NUMBER(5), --FK
    TOTAL NUMBER(10), --수량
    PRICE NUMBER(10) --금액
);

--상품
CREATE TABLE PRODUCT (
    PRODUCT_NO NUMBER(5) PRIMARY KEY,
    PRODUCT_NAME VARCHAR(20),
    TOTAL NUMBER(5),
    PRICE NUMBER(5)
);

INSERT INTO PRODUCT VALUES(1, '피자', 100, 10000); 
INSERT INTO PRODUCT VALUES(2, '치킨', 100, 15000); 
INSERT INTO PRODUCT VALUES(3, '햄버거', 100, 5000);

select*FROM PRODUCT;

CREATE OR REPLACE TRIGGER ORDER_BY
    AFTER INSERT
    on ORDER_HISTORY
    FOR EACH ROW
    
DECLARE
    v_CNT NUMBER :=0;
    V_NEW_NO NUMBER:=:NEW.PRODUCT_NO;
    V_TOTAL NUMBER:=:NEW.TOTAL;
BEGIN
    
     
    SELECT COUNT(*)
    INTO V_CNT
    FROM PRODUCT
    WHERE product_NO=V_NEW_NO;
    
    
    
    IF V_CNT=0 THEN
       dbms_output.put_line('재고가 부족합니다'); 
       return;
    ELSE
        UPDATE PRODUCT SET TOTAL=TOTAL-V_TOTAL where PRODUCT_NO=V_NEW_NO;
    END IF;
END;

INSERT INTO ORDER_HISTORY VALUES(1,2,3,10,1000);
select*FROM PROduct;

